name: CustomCommand
version: '2.4.1'
main: ontey.ccmd.Main
api-version: '1.21'
authors: [ Ontey ]
loader: ontey.ccmd.CustomCommandLoader
bootstrapper: ontey.ccmd.CustomCommandBootstrapper

dependencies:
  server:
    PlaceholderAPI:
      load: OMIT
      required: false