name: CustomCommand
version: '0.5'
main: com.ontey.Main
api-version: '1.21'
authors: [ Ontey ]
description: Easily create custom commands

softdepend: [PlaceholderAPI]

commands:
  customcommands:
    description: "The main command for the CustomCommand Plugin"
    usage: /<command> wiki|reload [all, commands, config]
    permission: customcommands.cmd.customcommand
    aliases: [ccmd]